// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DineinEasy.Data.Models;

public partial class Banner
{
    public int Id { get; set; }

    public DateTime? ExpriedDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string ImageUrl { get; set; }

    public bool? Status { get; set; }
}