// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DineinEasy.Data.Models;

public partial class Notification
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string Body { get; set; }

    public string ImageUrl { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid CustomerId { get; set; }
    [ForeignKey(nameof(CustomerId))]
    public virtual Customer Customer { get; set; }
}