// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DineinEasy.Data.Models;

public partial class OrderBooking
{
    public int Id { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? BookingDate { get; set; }

    public DateTime? BookingTime { get; set; }

    public int? NumberSeats { get; set; }

    public bool? IsChecking { get; set; }

    public int? CustomerId { get; set; }

    public int? RestaurantId { get; set; }

    public string Note { get; set; }

    public bool? Status { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Restaurant Restaurant { get; set; }
}