// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DineinEasy.Data.Models;

public partial class Restaurant
{
    public int Id { get; set; }

    public string Tags { get; set; }

    public DateTime CreateAt { get; set; }

    public double Longitude { get; set; }

    public double Latitude { get; set; }

    public string Address { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int NumberTable { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Avatar { get; set; }

    public DateTime UpdateAt { get; set; }

    public int CategoryId { get; set; }

    public double Rating { get; set; }

    public bool Status { get; set; }

    public int AreaId { get; set; }

    public virtual Area Area { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderBooking> OrderBookings { get; set; } = new List<OrderBooking>();

    public virtual ICollection<OrderMembership> OrderMemberships { get; set; } = new List<OrderMembership>();

    public virtual ICollection<RestaurantImage> RestaurantImages { get; set; } = new List<RestaurantImage>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<SavedRestaurant> SavedRestaurants { get; set; } = new List<SavedRestaurant>();

    public virtual ICollection<TimeFrame> TimeFrames { get; set; } = new List<TimeFrame>();
}