// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DineinEasy.Data.Models;

public partial class Review
{
    public int Id { get; set; }

    public int Number { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public Guid CustomerId { get; set; }

    public int RestaurantId { get; set; }

    public bool Status { get; set; }
    [ForeignKey(nameof(CustomerId))]
    public virtual Customer Customer { get; set; }

    public virtual Restaurant Restaurant { get; set; }

    public virtual ICollection<ReviewImage> ReviewImages { get; set; } = new List<ReviewImage>();
}