// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DineinEasy.Data.Models;

public partial class SavedRestaurant
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public Guid CustmerId { get; set; }

    public int RestaurantId { get; set; }

    [ForeignKey(nameof(CustmerId))]
    public virtual Customer Custmer { get; set; }

    public virtual Restaurant Restaurant { get; set; }
}