// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DineinEasy.Data.Models;

public partial class SavedRestaurant
{
    public int Id { get; set; }

    public int CustmerId { get; set; }

    public int RestaurantId { get; set; }

    public virtual Customer Custmer { get; set; }

    public virtual Restaurant Restaurant { get; set; }
}