// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DineinEasy.Data.Models;

public partial class TimeFrame
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public string Day { get; set; }

    public TimeOnly OpenedTime { get; set; }

    public TimeOnly ClosedTime { get; set; }

    public int RestaurantId { get; set; }

    public virtual Restaurant Restaurant { get; set; }
}